#!/bin/bash

allowed_extension()
{
	local EXTENSION=$(echo $1 | awk -F . '{print $NF}')
	local IGNORE=(~/.catignore)
	if [ -f $IGNORE ]; then
		local FORBIDDEN=$(cat $IGNORE)
	else
		local FORBIDDEN=(pdf o a)
	fi
	for FORB in ${FORBIDDEN[@]}
	do
		if [ $EXTENSION = $FORB ]; then
			echo "$IGNORE : *.$EXTENSION"
			false
			return
		fi
	done
	true
}

show_file()
{
	local FILE=$(echo $1 | cut -d " " -f9)
	local SIZE=$(echo $1 | cut -d " " -f5)
	local PERM=$(echo $1 | cut -d " " -f1)
	local AUTH=$(echo $1 | cut -d " " -f3)
	printf "\x1b[36m$FILE \t $SIZE \t $PERM \t $AUTH\\x1b[0m\n"
	if allowed_extension $FILE; then
		cat "$FILE"
	fi
}

if [ $# -eq 0 ]; then
	DIR=`pwd`
elif [ $# -eq 1 ]; then
	DIR=$1
	if [ ! -d $DIR ]; then
		if [ ! -f $DIR ]; then
			echo "$DIR does not exist."
			exit 1
		else
			show_file "$(ls -lh $1)"
			exit 1
		fi
	fi
	cd $DIR
	DIR=`pwd`
else
	echo "Too many arguments."
	exit 1
fi
echo "Directory : $DIR"
ls -lh | sed 1d | while read LINE;
do
	echo
	show_file "$LINE"
done
